name: AI Switchboard (hourly)

on:
  workflow_dispatch:
  push:
    paths:
      - 'ea/**'
      - 'data/inbox.chatgpt.json'
      - '.github/workflows/ai-switchboard.yml'
  schedule:
    - cron: '0 * * * *'  # hourly, UTC

permissions:
  contents: write   # needed to commit data/nomination.json
  actions: read

concurrency:
  group: ai-switchboard-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run switchboard
        run: node ea/switchboard.mjs data/inbox.chatgpt.json data/nomination.json

      - name: Upload decision artifact (debug/record)
        uses: actions/upload-artifact@v4
        with:
          name: nomination
          path: data/nomination.json

      # ✅ Auto-commit the decision so the site can read /data/nomination.json
      - name: Commit decision to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "EA: update nomination decision"
          file_pattern: data/nomination.json
