name: AI Switchboard (hourly)

on:
  schedule:
    - cron: "0 * * * *"    # hourly UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install deps
        run: npm ci || npm install
      - name: Run switchboard
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          XAI_API_KEY:       ${{ secrets.XAI_API_KEY }}
          XAI_BASEURL:       ${{ secrets.XAI_BASEURL }}
          XAI_MODEL:         ${{ secrets.XAI_MODEL }}
          GEMINI_API_KEY:    ${{ secrets.GEMINI_API_KEY }}
          OPENAI_API_KEY:    ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASEURL:    ${{ secrets.OPENAI_BASEURL }}
          LLAMA_MODEL:       ${{ secrets.LLAMA_MODEL }}
        run: npm run switchboard
      - name: Commit & push changes
        run: |
          git config user.name  "agauai-bot"
          git config user.email "actions@users.noreply.github.com"
          git add public/api/ai/*.json || true
          if [[ -n "$(git diff --cached --name-only)" ]]; then
            git commit -m "switchboard: inbox updates"
            git push
          else
            echo "No inbox changes to commit."
          fi
